### ISSUE TITLE
US3 - Criar página livros

### ISSUE THREAD

**Issue by thiagosoara** [paulo-00-ctrl/WordlFantasy#4]
Como INTERNAUTA, eu quero OBTER INFORMAÇÕES ACERCA DE LIVROS, para PODER COMPRAR E ESTAR ATUALIZADO SOBRE AS TENDêNCIAS.

**Comment by karolaynemiranda** [comment]
**criando a tabela com linhas e colunas que vai ter o nome como também a sinopse com o respectivo valor**
